apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techsolutions-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashwini-m-hub/microservices-ingress-day-7.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
